# Generated by Django 5.2 on 2025-06-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('domiciliario', 'Domiciliario'), ('tienda', 'Tienda')], default='c', max_length=20),
        ),
    ]
