# Generated by Django 5.2 on 2025-11-24 23:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import tasks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='domiciliario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='slug',
        ),
        migrations.AddField(
            model_name='domiciliario',
            name='documento_frontal',
            field=models.FileField(blank=True, null=True, upload_to='domiciliario/documentos/identidad/'),
        ),
        migrations.AddField(
            model_name='domiciliario',
            name='documento_trasera',
            field=models.FileField(blank=True, null=True, upload_to='domiciliario/documentos/identidad/'),
        ),
        migrations.AddField(
            model_name='domiciliario',
            name='estado_verificacion',
            field=models.CharField(choices=[('PENDIENTE_DOCUMENTOS', 'Pendiente de carga de documentos'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE_DOCUMENTOS', max_length=30),
        ),
        migrations.AddField(
            model_name='domiciliario',
            name='foto_perfil_domiciliario',
            field=models.ImageField(blank=True, null=True, upload_to='domiciliario/perfiles/'),
        ),
        migrations.AddField(
            model_name='domiciliario',
            name='licencia_conducir',
            field=models.FileField(blank=True, null=True, upload_to='domiciliario/documentos/licencias/'),
        ),
        migrations.AddField(
            model_name='domiciliario',
            name='soat',
            field=models.FileField(blank=True, null=True, upload_to='domiciliario/documentos/soat/'),
        ),
        migrations.AddField(
            model_name='domiciliario',
            name='tarjeta_propiedad',
            field=models.FileField(blank=True, null=True, upload_to='domiciliario/documentos/propiedad/'),
        ),
        migrations.AddField(
            model_name='productos',
            name='datos_extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='tienda',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'tienda'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.profile'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo_mascota',
            field=models.CharField(blank=True, choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='apellido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resenaproductomascota',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_producto_mascota', to='tasks.productos'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='nombre_tienda',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=tasks.models.generate_api_key, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tienda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='tasks.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tasks.cart')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_quien_recibe', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(default='Colombia', max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('info_adicional', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('es_predeterminada', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_recogida', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('ubicacion_entrega', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Esperando domiciliario'), ('EN_CURSO', 'Asignado, en camino a recoger'), ('EN_CAMINO', 'Recogido, en camino a entregar'), ('ENTREGADO', 'Completado')], default='DISPONIBLE', max_length=20)),
                ('codigo_entrega_tienda', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('codigo_recepcion_cliente', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.cliente')),
                ('domiciliario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.domiciliario')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tienda')),
            ],
        ),
    ]
