# Generated by Django 5.1.4 on 2025-01-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_productos_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='datecompleted',
        ),
    ]
