# Generated by Django 5.2 on 2025-06-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_profile_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='apellido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('domiciliario', 'Domiciliario'), ('tienda', 'Tienda')], default='cliente', max_length=20),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='nombre_tienda',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
