# Generated by Django 5.1.4 on 2025-01-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lastname',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='profile',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
