# Generated by Django 5.1.4 on 2025-01-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_lastname_profile_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='usuario',
        ),
    ]
