# Generated by Django 5.2 on 2025-04-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_profile_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fechaNacimiento',
        ),
        migrations.AddField(
            model_name='profile',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
