# Generated by Django 5.2 on 2025-07-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='domiciliario',
            name='documento_frontal',
            field=models.FileField(blank=True, null=True, upload_to='domiciliarios/documentos/identidad/'),
        ),
        migrations.AddField(
            model_name='domiciliario',
            name='documento_trasera',
            field=models.FileField(blank=True, null=True, upload_to='domiciliarios/documentos/identidad/'),
        ),
        migrations.AddField(
            model_name='domiciliario',
            name='estado_verificacion',
            field=models.CharField(choices=[('PENDIENTE_DOCUMENTOS', 'Pendiente de carga de documentos'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE_DOCUMENTOS', max_length=30),
        ),
        migrations.AddField(
            model_name='domiciliario',
            name='foto_perfil_domiciliario',
            field=models.ImageField(blank=True, null=True, upload_to='domiciliarios/perfiles/'),
        ),
        migrations.AddField(
            model_name='domiciliario',
            name='licencia_conducir',
            field=models.FileField(blank=True, null=True, upload_to='domiciliarios/documentos/licencias/'),
        ),
        migrations.AddField(
            model_name='domiciliario',
            name='soat',
            field=models.FileField(blank=True, null=True, upload_to='domiciliarios/documentos/soat/'),
        ),
        migrations.AddField(
            model_name='domiciliario',
            name='tarjeta_propiedad',
            field=models.FileField(blank=True, null=True, upload_to='domiciliarios/documentos/propiedad/'),
        ),
    ]
