# Generated by Django 5.2 on 2025-08-26 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_domiciliario_documento_frontal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domiciliario',
            name='documento_frontal',
            field=models.FileField(blank=True, null=True, upload_to='domiciliario/documentos/identidad/'),
        ),
        migrations.AlterField(
            model_name='domiciliario',
            name='documento_trasera',
            field=models.FileField(blank=True, null=True, upload_to='domiciliario/documentos/identidad/'),
        ),
        migrations.AlterField(
            model_name='domiciliario',
            name='foto_perfil_domiciliario',
            field=models.ImageField(blank=True, null=True, upload_to='domiciliario/perfiles/'),
        ),
        migrations.AlterField(
            model_name='domiciliario',
            name='licencia_conducir',
            field=models.FileField(blank=True, null=True, upload_to='domiciliario/documentos/licencias/'),
        ),
        migrations.AlterField(
            model_name='domiciliario',
            name='soat',
            field=models.FileField(blank=True, null=True, upload_to='domiciliario/documentos/soat/'),
        ),
        migrations.AlterField(
            model_name='domiciliario',
            name='tarjeta_propiedad',
            field=models.FileField(blank=True, null=True, upload_to='domiciliario/documentos/propiedad/'),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_quien_recibe', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(default='Colombia', max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('info_adicional', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('es_predeterminada', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.profile')),
            ],
        ),
    ]
