# Generated by Django 5.2 on 2025-09-29 19:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_domiciliario_documento_frontal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_recogida', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('ubicacion_entrega', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Esperando domiciliario'), ('EN_CURSO', 'Asignado, en camino a recoger'), ('EN_CAMINO', 'Recogido, en camino a entregar'), ('ENTREGADO', 'Completado')], default='DISPONIBLE', max_length=20)),
                ('codigo_entrega_tienda', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('codigo_recepcion_cliente', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.cliente')),
                ('domiciliario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.domiciliario')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tienda')),
            ],
        ),
    ]
