# Generated by Django 5.2 on 2025-11-04 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_tienda_ubicacion_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='slug',
        ),
        migrations.AddField(
            model_name='productos',
            name='datos_extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='tienda',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'tienda'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.profile'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo_mascota',
            field=models.CharField(blank=True, choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tienda', models.OneToOneField(limit_choices_to={'tipo_usuario': 'tienda'}, on_delete=django.db.models.deletion.CASCADE, to='tasks.profile')),
            ],
        ),
    ]
